_BASE_: "../../defrcn_gfsod_r101_novelx_1shot_seedx.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_MULTIPROTO: True
  PCB_MULTIPROTO_K: 3
  PCB_MULTIPROTO_MATCH: "max"
