_BASE_: "../../adapterAblations/baseline/defrcn_det_r101_base1_adapter.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_MULTIPROTO: True
  PCB_MULTIPROTO_K: 3
  PCB_MULTIPROTO_MATCH: "max"
