_BASE_: "../baseline/defrcn_fsod_r101_novelx_1shot_seedx_adapter.yaml"
MODEL:
  BRANCH_ADAPTER:
    NORM: "LN"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (1280, )
  MAX_ITER: 1600
  CHECKPOINT_PERIOD: 200000
  WARMUP_ITERS: 0
