from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster

# -------- Dual Fusion Neck ------ #
_CC.MODEL.DUAL_FUSION = CN()
_CC.MODEL.DUAL_FUSION.ENABLE = False
_CC.MODEL.DUAL_FUSION.IN_FEATURES = ["res3", "res4", "res5"]
_CC.MODEL.DUAL_FUSION.OUT_FEATURE = "res4"
_CC.MODEL.DUAL_FUSION.ALIGN_CHANNELS = 1024
_CC.MODEL.DUAL_FUSION.USE_REFINE = True
# Strong res3/res4, moderate res5
_CC.MODEL.DUAL_FUSION.RPN_INIT_LOGITS = [2.0, 1.5, 0.5]
# Strong res3/res4, near-zero res5
_CC.MODEL.DUAL_FUSION.ROI_INIT_LOGITS = [2.0, 1.5, -3.0]
_CC.MODEL.DUAL_FUSION.RPN_LEVELS = ["res3", "res4", "res5"]
_CC.MODEL.DUAL_FUSION.ROI_LEVELS = ["res3", "res4"]

# ------ Branch Adapter Neck ----- #
_CC.MODEL.BRANCH_ADAPTER = CN()
_CC.MODEL.BRANCH_ADAPTER.ENABLE = False
_CC.MODEL.BRANCH_ADAPTER.RPN_FEATURES = ["res4"]
_CC.MODEL.BRANCH_ADAPTER.ROI_FEATURES = ["res4"]
_CC.MODEL.BRANCH_ADAPTER.SHARED = False
_CC.MODEL.BRANCH_ADAPTER.BOTTLENECK_RATIO = 0.25
_CC.MODEL.BRANCH_ADAPTER.MIN_CHANNELS = 64
_CC.MODEL.BRANCH_ADAPTER.NORM = "GN"  # GN, LN, NONE
_CC.MODEL.BRANCH_ADAPTER.GN_NUM_GROUPS = 32
_CC.MODEL.BRANCH_ADAPTER.USE_GATE = True
_CC.MODEL.BRANCH_ADAPTER.GATE_INIT = 0.0
_CC.MODEL.BRANCH_ADAPTER.ZERO_INIT_LAST = True

# ----------- VAE-FSOD ----------- #
_CC.MODEL.VAE_FSOD = CN()
_CC.MODEL.VAE_FSOD.ENABLE = False
_CC.MODEL.VAE_FSOD.FEATURE_BANK_PATH = ""
_CC.MODEL.VAE_FSOD.AUX_LOSS_WEIGHT = 1.0
_CC.MODEL.VAE_FSOD.AUX_BATCH_SIZE = 64

# Paper-aligned architecture/settings
_CC.MODEL.VAE_FSOD.FEATURE_DIM = 2048
_CC.MODEL.VAE_FSOD.SEMANTIC_SOURCE = "clip"
_CC.MODEL.VAE_FSOD.SEMANTIC_DIM = 512
_CC.MODEL.VAE_FSOD.LATENT_DIM = 512
_CC.MODEL.VAE_FSOD.ENCODER_HIDDEN = 4096
_CC.MODEL.VAE_FSOD.DECODER_HIDDEN = 4096

# IoU->norm mapping from paper
_CC.MODEL.VAE_FSOD.IOU_MIN = 0.5
_CC.MODEL.VAE_FSOD.IOU_MAX = 1.0
_CC.MODEL.VAE_FSOD.NORM_MIN_FACTOR = 1.0   # sqrt(latent_dim) * factor
_CC.MODEL.VAE_FSOD.NORM_MAX_FACTOR = 5.0   # sqrt(latent_dim) * factor
_CC.MODEL.VAE_FSOD.BETA_INTERVAL = 0.75
_CC.MODEL.VAE_FSOD.NUM_GEN_PER_CLASS = 30

# Quality-conditioned VAE extension (modular, optional).
_CC.MODEL.VAE_FSOD.QUALITY = CN()
_CC.MODEL.VAE_FSOD.QUALITY.ENABLE = False
_CC.MODEL.VAE_FSOD.QUALITY.KEYS = ["iou", "fg_ratio", "gt_coverage", "center_offset", "crowding"]
_CC.MODEL.VAE_FSOD.QUALITY.AUX_LOSS_WEIGHT = 0.2
_CC.MODEL.VAE_FSOD.QUALITY.AUX_LOSS_TYPE = "smooth_l1"  # smooth_l1, mse, l1
_CC.MODEL.VAE_FSOD.QUALITY.HARDNESS_WEIGHTS = [1.0, 1.0, 1.0, 1.0, 0.5]
_CC.MODEL.VAE_FSOD.QUALITY.BIN_QUANTILES = [0.33, 0.66]
_CC.MODEL.VAE_FSOD.QUALITY.GEN_BIN_RATIOS = [0.34, 0.33, 0.33]  # easy, medium, hard
_CC.MODEL.VAE_FSOD.QUALITY.MAX_BANK_PER_CLASS_BIN = 512

# VAE training settings
_CC.MODEL.VAE_FSOD.TRAIN_BATCH_SIZE = 256
_CC.MODEL.VAE_FSOD.TRAIN_EPOCHS = 20
_CC.MODEL.VAE_FSOD.TRAIN_LR = 1e-4
_CC.MODEL.VAE_FSOD.TRAIN_WEIGHT_DECAY = 1e-5
_CC.MODEL.VAE_FSOD.RECON_LOSS_WEIGHT = 1.0
_CC.MODEL.VAE_FSOD.KL_LOSS_WEIGHT = 1.0
_CC.MODEL.VAE_FSOD.AUG_PER_BOX = 10
_CC.MODEL.VAE_FSOD.AUG_BOX_SCALE_MAX = 0.3
_CC.MODEL.VAE_FSOD.MAX_ROIS = 200000

# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = "resnet"             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# PCB inference-only modular options
# 1) Quality-weighted prototypes
_CC.TEST.PCB_QUALITY_WEIGHTED = False
_CC.TEST.PCB_QUALITY_POWER = 1.0
_CC.TEST.PCB_QUALITY_MIN_WEIGHT = 0.05
_CC.TEST.PCB_TINY_AREA_THRESH = 0.01
_CC.TEST.PCB_AREA_POWER = 0.5
_CC.TEST.PCB_CROWD_PENALTY = 0.15

# 2) Multi-prototype per class
_CC.TEST.PCB_MULTIPROTO = False
_CC.TEST.PCB_MULTIPROTO_K = 2
_CC.TEST.PCB_MULTIPROTO_ITERS = 8
_CC.TEST.PCB_MULTIPROTO_MATCH = "max"  # max, softmax
_CC.TEST.PCB_MULTIPROTO_TEMP = 0.07

# 3) Scale-aware matching
_CC.TEST.PCB_SCALE_AWARE = False
_CC.TEST.PCB_SCALE_THRESH = [0.01, 0.05]  # normalized box area thresholds

# 4) Adaptive alpha fusion
_CC.TEST.PCB_ADAPTIVE_ALPHA = False
_CC.TEST.PCB_ALPHA_MIN = 0.30
_CC.TEST.PCB_ALPHA_MAX = 0.98
_CC.TEST.PCB_ALPHA_RELIABILITY_POWER = 1.0
_CC.TEST.PCB_ALPHA_SIM_POWER = 1.0
_CC.TEST.PCB_ALPHA_USE_SIMILARITY = True

# 5) Outlier-robust aggregation
_CC.TEST.PCB_ROBUST_AGG = False
_CC.TEST.PCB_ROBUST_MODE = "trimmed_mean"  # trimmed_mean, medoid
_CC.TEST.PCB_TRIM_RATIO = 0.2

# 6) Class-conditional calibration gating
_CC.TEST.PCB_CLASS_GATE = False
_CC.TEST.PCB_CLASS_GATE_MODE = "weaken"  # weaken, skip
_CC.TEST.PCB_CLASS_GATE_TINY_RATIO = 0.60
_CC.TEST.PCB_CLASS_GATE_MIN_QUALITY = 0.20
_CC.TEST.PCB_CLASS_GATE_WEAKEN = 0.35
_CC.TEST.PCB_CLASS_GATE_MIN_SAMPLES = 2

# 7) Post-calibration score normalization
_CC.TEST.PCB_SCORE_NORM = False
_CC.TEST.PCB_SCORE_NORM_BASE_TEMP = 1.0
_CC.TEST.PCB_SCORE_NORM_MAX_TEMP = 2.5
_CC.TEST.PCB_SCORE_NORM_POWER = 1.0
_CC.TEST.PCB_SCORE_CLAMP_EPS = 1e-4

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True
