_BASE_: "../../defrcn_fsod_r101_novelx_10shot_seedx.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_ROBUST_AGG: True
  PCB_ROBUST_MODE: "trimmed_mean"
  PCB_TRIM_RATIO: 0.20
