_BASE_: "../../adapterAblations/baseline/defrcn_fsod_r101_novel1_1shot_seed0_adapter.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_ROBUST_AGG: True
  PCB_ROBUST_MODE: "trimmed_mean"
  PCB_TRIM_RATIO: 0.20
