_BASE_: "../baseline/defrcn_fsod_r101_novelx_3shot_seedx_adapter.yaml"
MODEL:
  BRANCH_ADAPTER:
    RPN_FEATURES: []
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (2560,)
  MAX_ITER: 3200
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
