_BASE_: "../baseline/defrcn_gfsod_r101_novelx_1shot_seedx_adapter.yaml"
MODEL:
  BRANCH_ADAPTER:
    GATE_INIT: 1.0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (800, )
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
