_BASE_: "../../adapterAblations/baseline/defrcn_fsod_r101_novelx_10shot_seedx_adapter.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_SCALE_AWARE: True
  PCB_SCALE_THRESH: [0.01, 0.05]
