_BASE_: "../../adapterAblations/baseline/defrcn_gfsod_r101_novelx_1shot_seedx_adapter.yaml"
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  PCB_ADAPTIVE_ALPHA: True
  PCB_ALPHA_MIN: 0.50
  PCB_ALPHA_MAX: 0.99
